export const state = {
  session: {
    status: "idle",
    stage: "idle",
    projectId: null,
    projectName: null,
    message: "Todo detenido",
    startedAt: null,
  },
  components: {
    status: "stopped",
    url: null,
    version: null,
    tag: null,
    external: false,
  },
  shell: {
    status: "stopped",
    url: null,
    projectId: null,
    name: null,
    appName: null,
    external: false,
  },
  microfrontend: {
    status: "stopped",
    projectId: null,
    id: null,
    name: null,
    version: null,
  },
  microfrontendBranch: {
    status: "idle",
    projectId: null,
    microfrontendId: null,
    phase: null,
    message: null,
    error: null,
    startedAt: null,
  },
  microfrontendBuild: {
    status: "idle",
    projectId: null,
    microfrontendId: null,
    phase: null,
    message: null,
    error: null,
    startedAt: null,
  },
  microfrontendOperations: {},
  build: {
    status: "idle",
    tag: null,
    action: null,
    message: "Sin compilaciones en curso",
    startedAt: null,
  },
  execution: {
    status: "idle",
    projectId: null,
    projectName: null,
    steps: [],
    error: null,
    startedAt: null,
    endedAt: null,
  },
  browserPrompt: null,
};
